Rails.application.routes.draw do
  get '/' => 'home#top'
  get 'top' => 'home#top'
  get 'about' => 'home#about'
  get 'post' => 'post#index'
  get 'users' => 'users#index'
  get 'users/:id/edit' => 'users#edit'
  post 'users/:id/update' => 'users#update'
  get 'users/:id' => 'users#show'
  post 'users/create' => 'users#create'
  get 'signup' => 'users#new'
  get 'login' => 'users#login_form'
  get 'post/new' => 'post#new'
  post 'post/create' => 'post#create'
  get 'post/:id/edit' => 'post#edit'
  post 'post/:id/update' => 'post#update'
  post 'post/:id/destroy' => 'post#destroy'
  get 'post/:id' => 'post#show'
end
